=== ChaseZellers/czellers.github.io/Hotels.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Hotels">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Hotel" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string" />
              <xs:element name="Address" type="xs:string" />
              <xs:element name="Rooms" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="RoomNumber" type="xs:int" />
                    <xs:element name="Type" type="xs:string" />
                    <xs:element name="Price" type="xs:decimal" />
                    <xs:element name="Available" type="xs:boolean" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="HotelID" type="xs:int" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== ChaseZellers/czellers.github.io/Hotels.xml
<?xml version="1.0" encoding="utf-8" ?>
<Hotels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Hotels.xsd">

  <Hotel HotelID="101">
    <Name>Ocean View Inn</Name>
    <Address>123 Beach Road</Address>
    <Rooms>
      <RoomNumber>101</RoomNumber>
      <Type>Deluxe</Type>
      <Price>150.00</Price>
      <Available>true</Available>
    </Rooms>
    <Rooms>
      <RoomNumber>102</RoomNumber>
      <Type>Standard</Type>
      <Price>100.00</Price>
      <Available>false</Available>
    </Rooms>
  </Hotel>

  <Hotel HotelID="102">
    <Name>Mountain Lodge</Name>
    <Address>456 Hilltop Avenue</Address>
    <Rooms>
      <RoomNumber>201</RoomNumber>
      <Type>Suite</Type>
      <Price>200.00</Price>
      <Available>true</Available>
    </Rooms>
  </Hotel>

</Hotels>

=== ChaseZellers/czellers.github.io/HotelsErrors.xml
<?xml version="1.0" encoding="utf-8" ?>
<Hotels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Hotels.xsd">

  <Hotel>
    <Name>Broken Hotel</Name>
    <Address>999 Broken Blvd</Address>
    <Rooms>
      <RoomNumber>999</RoomNumber>
      <Type>Penthouse</Type>
      <Price>500.00</Price>
      <Available>true</Available>
    </Rooms>
  </Hotel>

  <Hotel HotelID="103">
    <Name>Another Hotel</Name>
    <Address>789 Avenue</Address>
    <Rooms>
      <RoomNumber>ABC</RoomNumber>
      <Type>Standard</Type>
      <Price>120.00</Price>
      <Available>false</Available>
    </Rooms>
  </Hotel>

  <Hotel HotelID="104">
    <Name>Yet Another Hotel</Name>
    <Address>321 Central St</Address>
    <Rooms>
      <RoomNumber>103</RoomNumber>
      <Type>Economy</Type>
      <Price>90.00</Price>
    </Rooms>
  </Hotel>

</Hotels>
